version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "travelappv3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y5fobkyv9tou"
s3_prefix = "travelappv3"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
